#!/usr/bin/env bash

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	File_path=$1
	server_ip=$2
	ssh_key=$4

	scp -0 StrichHostKeyChecking=no -i "$ssh_key" "$File_path" "$username@$server_ip":~
fi
